replicaCount: 2

image:
  repository: 928413605425.dkr.ecr.us-east-1.amazonaws.com/crud-backend
  tag: version3

service:
  type: ClusterIP
  port: 80

container:
  port: 8080
  
ingress:
  enabled: true
  path: /staging/api
  order: "2"
  
env:
  SPRING_PROFILES_ACTIVE: staging
  DB_HOST: database-1.c0f08e8sy7uu.us-east-1.rds.amazonaws.com
  DB_PORT: 3306
  DB_NAME: app_db
  DB_USERNAME: root
  DB_PASSWORD: password
