replicaCount: 1

image:
  repository: 928413605425.dkr.ecr.us-east-1.amazonaws.com/crud-backend
  tag: 043517e36388430487fb18c006d5177627ffb763

service:
  type: ClusterIP
  port: 80

container:
  port: 8080

ingress:
  enabled: true
  albName: dev-alb

env:
  SPRING_PROFILES_ACTIVE: dev

