replicaCount: 1

image:
  repository: 928413605425.dkr.ecr.us-east-1.amazonaws.com/crud-backend
  tag: a34336bd262e616c21672855c59c3e63c17675dd

service:
  type: ClusterIP
  port: 80

container:
  port: 8080

ingress:
  enabled: true
  albName: dev-alb

env:
  SPRING_PROFILES_ACTIVE: dev

