replicaCount: 1

image:
  repository: 928413605425.dkr.ecr.us-east-1.amazonaws.com/crud-backend
  tag: 3e27d74c9335a067fc9420c50990d60df4bdf3ba

service:
  type: ClusterIP
  port: 80

container:
  port: 8080

ingress:
  enabled: true
  albName: dev-alb

env:
  SPRING_PROFILES_ACTIVE: dev

